print ('what is your name?')
name=raw_input()
print ('Hello',name+',', 'How old are you?')
age=input()
print ('Good age,', 'Where do you live?')
location=raw_input()
location=location.upper()
print ('Great pleased to meet you,',name,'from',location)
